### ISSUE TITLE
Now that i have updated to 0.15, i still get the   error with bevy_asset_loader 

### ISSUE THREAD

**Issue by ethereumdegen** [AmionSky/bevy_obj#21]
Hi i know you closed my issue but i am still having this problem.  

Your suggestion that i can run 'cargo update' did not work.   I have tested and proven that this works for me:

```
 bevy_obj=  {path="../bevy_obj" ,  default-features = false , features= ["mesh"] }   

```

and this does not :

```
  bevy_obj=  {version = "0.15",  default-features = false , features= ["mesh"] }   

```

The only difference is my local repo is this :
https://github.com/ethereumdegen/bevy_obj

meaning it has this change :

https://github.com/ethereumdegen/bevy_obj/commit/41873d07a955f26e33c4c07ee7cda9a550d60025

So  please update the actual package to  have this change as well so  that i dont have to use my own fork.  Thanks

**Comment by ethereumdegen** [comment]
btw the error i get with 

```
 bevy_obj=  {version = "0.15",  default-features = false , features= ["mesh"] }   
```

is the following: 

The target Handle<bevy_mesh::mesh::Mesh>'s TypeId does not match the TypeId of this UntypedHandle
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_asset_loader::loading_state::systems::check_loading_collection<main::asset_loading::AssetLoadState, main::asset_loading::MeshAssets>`!
Encountered a panic in system `bevy_asset_loader::loading_state::systems::run_loading_state<main::asset_loading::AssetLoadState>`!

**Comment by AmionSky** [comment]
Could you share the Cargo.lock file of both the working and the non-working version of the project?

**Comment by AmionSky** [comment]
I checked out `bevy_asset_loader` to recreate the error. I was able to get the same error if I did not disable the `scene` feature on this crate. But if I do it works fine.

Once again I highly doubt that the issue is the `-rc` because Cargo.lock file shows that it just resolves to bevy 0.15.0.

My test project:
[testthisthing.zip](https://github.com/user-attachments/files/18221473/testthisthing.zip)

**Comment by ethereumdegen** [comment]
https://gist.github.com/ethereumdegen/d44c00baa30abaf755d2ca0d3fccd4a3   

i am not accidentally adding the scene feature, only mesh.  I am seeing something different than you.   here my cargo lock.  

The repo that is having the issue is public btw 

https://github.com/ethereumdegen/spirit_editor 

(but kind of tricky to get running bc of how i gitignore some assets but you can take a look yourself)

**Comment by AmionSky** [comment]
I think I found your issue. maybe

You pull in the dependency `bevy_magic_fx` (it seems to be yours too) that uses `bevy_obj` as well, but the version on crates.io declares it without "default-features= false".

So when you use the crates.io version of `bevy_obj` then the scene feature gets pulled in because it isn't disabled in `bevy_magic_fx` (because cargo features are additive)

But when you use your own fork of `bevy_obj` it counts as a separate crates from the crates.io so the features does not get added.

**Comment by AmionSky** [comment]
From what I seen `bevy_magic_fx ` only uses `bevy_obj` in examples so you could just move that dependency to dev-dependencies.
